---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-config.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-config.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "safe-config.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "safe-config.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: config
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
        resources:
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "safe-config.fullname" . }}
          - secretRef:
              {{- if .Values.config.secretReferenceKey }}
              name: {{ .Values.config.secretReferenceKey }}
              {{- else }}
              name: {{ include "safe-config.fullname" . }}
              {{- end }}
          - secretRef:
              name: {{ include "safe-config.postgres-secret" . }}
        ports:
        - containerPort: {{ .Values.service.socket.number }}
          name: {{ .Values.service.socket.name }}
          protocol: TCP
        volumeMounts:
          - name: content-volume
            mountPath: /nginx
          - name: tmp-volume
            mountPath: /tmp
      - name: web
        image: "registry.hub.docker.com/library/nginx:alpine"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        {{- end }}
        # env:
        #   - name: NGINX_ENTRYPOINT_QUIET_LOGS
        #     value: "true"
        ports:
        - containerPort: {{ .Values.service.ports.number }}
          name: {{ .Values.service.ports.name }}
          protocol: TCP
        volumeMounts:
          - name: nginx-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: content-volume
            mountPath: /nginx
          - name: tmp-volume
            mountPath: /tmp
          - name: cache-volume
            mountPath: /var/cache/nginx
      serviceAccountName: {{ include "safe-config.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: content-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {} 
        - name: nginx-volume
          configMap:
            name: {{ include "safe-config.fullname" . }}-nginx
        - name: cache-volume
          emptyDir: {} 

